name: 'Fetch Github Release Asset'
description: 'Downloads an asset from a Github release'

inputs:
  repo:
    description: 'The `org/repo` containing the release.'
    required: false
    default: ''
  version:
    description: 'The release version to fetch from in the form `tags/<tag_name>` or `<release_id>`.'
    required: false
    default: 'latest'
  file:
    description: 'The name of the file to be downloaded.'
    required: true
  target:
    description: 'Target file path.'
    required: false
  token:
    description: 'The GitHub token. Typically this will be secrets.GITHUB_TOKEN'
    required: false
    default: ${{ github.token }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.version }}
    - ${{ inputs.file }}
    - ${{ inputs.target }}
    - ${{ inputs.token }}

outputs:
  version:
    description: 'The version of the release or tag'
  name:
    description: 'The name of the release'
  body:
    description: 'The body of the release'

branding:
  icon: 'download-cloud'
  color: 'orange'
